version: "3"
services:
  inttest:
    build:
      context: ..
      dockerfile: Dockerfile.inttest
    environment:
      NETCONF_DUT_SSHHOST: confd
      NETCONF_DUT_SSHPORT: 2022
      NETCONF_DUT_SSHUSER: admin
      NETCONF_DUT_SSHPASS: admin
      NETCONF_DUT_FLAVOR: confd
    depends_on:
      - confd
    command: >
      sh -c "./wait-for-hello.sh
      -s $$NETCONF_DUT_SSHPASS
      -p $$NETCONF_DUT_SSHPORT
      $$NETCONF_DUT_SSHUSER@$$NETCONF_DUT_SSHHOST &&
      CGO_ENABLED=0 go test -tags=inttest -v ."
  confd:
    image: ${CONFD_IMAGE:?}
    platform: "linux/amd64"
    privileged: true
    tty: true
    stop_signal: SIGKILL