version: "3"
services:
  inttest:
    build:
      context: ..
      dockerfile: Dockerfile
      target: inttest
    environment:
      NETCONF_DUT_SSHHOST: netopeer2
      NETCONF_DUT_SSHPORT: 830
      NETCONF_DUT_SSHUSER: netconf
      NETCONF_DUT_SSHPASS: netconf
      NETCONF_DUT_FLAVOR: netopeer2
    depends_on:
      - netopeer2
    command: >
      sh -c "./wait-for-hello.sh
      -s $$NETCONF_DUT_SSHPASS
      -p $$NETCONF_DUT_SSHPORT
      $$NETCONF_DUT_SSHUSER@$$NETCONF_DUT_SSHHOST &&
      ./inttest.test -test.v"
  netopeer2:
    build:
      context: .
      dockerfile: Dockerfile.netopeer2