version: "3"
services:
  inttest:
    build:
      context: ..
      dockerfile: Dockerfile.inttest
    environment:
      NETCONF_DUT_SSHHOST: csrx
      NETCONF_DUT_SSHPORT: 22
      NETCONF_DUT_SSHADDR: csrx:22
      NETCONF_DUT_SSHUSER: root
      NETCONF_DUT_SSHPASS: juniper123
      NETCONF_DUT_FLAVOR: junos
    depends_on:
      - csrx
    command: >
      sh -c "./wait-for-hello.sh
      -s $$NETCONF_DUT_SSHPASS
      -p $$NETCONF_DUT_SSHPORT
      $$NETCONF_DUT_SSHUSER@$$NETCONF_DUT_SSHHOST &&
      CGO_ENABLED=0 go test -v ."
  csrx:
    image: ${CSRX_IMAGE:?}
    environment:
      - CSRX_JUNOS_CONFIG=/root/initial.conf
    privileged: true
    stop_signal: SIGTERM
    volumes:
      - ./csrx.conf:/root/initial.conf:ro
